# Generated by Django 5.2.8 on 2025-11-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_form_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltransactions',
            name='emr_file',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/'),
        ),
        migrations.AddField(
            model_name='medicaltransactions',
            name='his_file',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/'),
        ),
    ]
