# Generated by Django 5.2.8 on 2025-11-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_form_assistant', '0002_medicaltransactions_emr_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='barangay',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Barangay'),
        ),
        migrations.AddField(
            model_name='patient',
            name='building_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Building Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='city_municipality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City/Municipality'),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='landline_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Landline No. (Area Code + Tel. No.)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='lot_blk_house_bldg_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lot/Blk/House/Bldg.No'),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile No.'),
        ),
        migrations.AddField(
            model_name='patient',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='patient',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='patient',
            name='subdivision_village',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subdivision/Village'),
        ),
        migrations.AddField(
            model_name='patient',
            name='unit_room_no_floor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit/Room No./Floor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip Code'),
        ),
    ]
